# -*- coding: utf-8 -*-
"""Label Designer App

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lt6NzwMcYxrZJUwfv6lZ3ufPbht8MChu
"""

import streamlit as st
import streamlit.components.v1 as components

# 1. Configure the Streamlit Page
st.set_page_config(
    page_title="Label Designer Pro",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# 2. Optional: Add Streamlit native controls if you want to mix Python and HTML
# (For this specific app, the HTML handles everything better, so we keep it clean)
st.title("🏷️ Label Designer Pro")
st.markdown("Powered by **Streamlit** and **HTML5 Canvas**")

# 3. Define the HTML/JS Code
# We embed the exact code to preserve the smooth Drag & Drop functionality
html_code = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Label Designer Pro</title>

    <!-- Load External Libraries -->
    <script src="https://cdn.jsdelivr.net/npm/jsbarcode@3.11.5/dist/JsBarcode.all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">

    <style>
        :root {
            --primary-color: #4f46e5;
            --primary-hover: #4338ca;
            --bg-color: #f3f4f6;
            --panel-bg: #ffffff;
            --text-color: #1f2937;
            --border-color: #e5e7eb;
            --danger-color: #ef4444;
        }
        * { box-sizing: border-box; outline: none; }
        body {
            font-family: 'Inter', sans-serif;
            background-color: var(--bg-color);
            color: var(--text-color);
            margin: 0;
            display: flex;
            overflow: hidden;
            height: 100vh; /* Full height for iframe */
        }

        /* Layout adjustments for Streamlit iframe */
        .sidebar {
            width: 300px;
            background: var(--panel-bg);
            border-right: 1px solid var(--border-color);
            display: flex;
            flex-direction: column;
            padding: 20px;
            gap: 20px;
            overflow-y: auto;
        }
        .main-content {
            flex: 1;
            display: flex;
            flex-direction: column;
            position: relative;
            height: 100%;
        }
        .toolbar {
            height: 60px;
            background: var(--panel-bg);
            border-bottom: 1px solid var(--border-color);
            display: flex;
            align-items: center;
            padding: 0 20px;
            justify-content: space-between;
        }
        .canvas-container {
            flex: 1;
            background-color: #e5e7eb;
            background-image: radial-gradient(#d1d5db 1px, transparent 1px);
            background-size: 20px 20px;
            display: flex;
            align-items: center;
            justify-content: center;
            overflow: auto;
            position: relative;
        }
        .code-panel {
            width: 280px;
            background: #1e293b;
            color: #e2e8f0;
            border-left: 1px solid var(--border-color);
            display: flex;
            flex-direction: column;
            padding: 20px;
        }

        /* Components */
        h2 { font-size: 1rem; color: var(--primary-color); margin: 0 0 10px 0; }
        label { display: block; margin-bottom: 5px; font-size: 0.8rem; font-weight: 600; color: #4b5563; }
        input, select {
            width: 100%; padding: 8px; border: 1px solid var(--border-color);
            border-radius: 6px; margin-bottom: 10px;
        }
        .btn {
            padding: 8px 12px; border: none; border-radius: 6px; cursor: pointer;
            font-size: 0.85rem; display: inline-flex; align-items: center; gap: 8px;
        }
        .btn-primary { background: var(--primary-color); color: white; }
        .btn-outline { background: white; border: 1px solid var(--border-color); }
        .btn-danger { background: #fee2e2; color: var(--danger-color); }

        /* Canvas Wrapper */
        #canvasWrapper {
            background: white;
            box-shadow: 0 10px 25px rgba(0,0,0,0.1);
            transition: transform 0.2s;
            transform-origin: center center;
        }

        /* Layers */
        .layer-item {
            padding: 8px; background: white; border: 1px solid var(--border-color);
            border-radius: 6px; cursor: pointer; display: flex; justify-content: space-between;
            margin-bottom: 5px; align-items: center;
        }
        .layer-item.selected { border-color: var(--primary-color); background: #eef2ff; }

        /* Properties */
        .properties-panel { background: white; border: 1px solid var(--border-color); padding: 10px; border-radius: 8px; display: none; }
        .properties-panel.active { display: block; }

        /* Zoom */
        .zoom-control {
            position: absolute; bottom: 20px; left: 50%; transform: translateX(-50%);
            background: white; padding: 5px 15px; border-radius: 20px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1); display: flex; align-items: center; gap: 10px;
        }

        .grid-2 { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
        .hidden { display: none !important; }
    </style>
</head>
<body>

    <!-- Sidebar -->
    <div class="sidebar">
        <h2 style="font-size: 1.2rem; color: #1f2937;"><i class="fas fa-tag"></i> Label Pro</h2>

        <div>
            <label>Canvas Size (mm)</label>
            <div class="grid-2">
                <input type="number" id="canvasW" value="50" onchange="initCanvas()">
                <input type="number" id="canvasH" value="30" onchange="initCanvas()">
            </div>
        </div>

        <!-- Dynamic Properties -->
        <div id="propPanel" class="properties-panel">
            <div style="display:flex; justify-content:space-between; margin-bottom:10px;">
                <label>Properties</label>
                <button class="btn-danger" style="padding:2px 8px;" onclick="deleteItem()">×</button>
            </div>
            <input type="text" id="propValue" oninput="updateItem('value', this.value)" placeholder="Content">

            <div class="grid-2">
                <div><label>X</label><input type="number" id="propX" oninput="updateItem('x', this.value)"></div>
                <div><label>Y</label><input type="number" id="propY" oninput="updateItem('y', this.value)"></div>
            </div>

            <div class="grid-2">
                <div><label id="lblH">Height</label><input type="number" id="propH" oninput="updateItem('h', this.value)"></div>
                <div><label>Scale</label><input type="number" id="propScale" oninput="updateItem('scale', this.value)" step="0.1"></div>
            </div>

            <div id="textOptions">
                 <label><input type="checkbox" id="propBold" onchange="updateItem('bold', this.checked)"> Bold</label>
            </div>
        </div>

        <!-- Add Items -->
        <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 5px;">
            <button class="btn btn-outline" onclick="addItem('text')"><i class="fas fa-font"></i></button>
            <button class="btn btn-outline" onclick="addItem('barcode')"><i class="fas fa-barcode"></i></button>
            <button class="btn btn-outline" onclick="addItem('qr')"><i class="fas fa-qrcode"></i></button>
        </div>

        <!-- Layer List -->
        <div style="flex:1; overflow-y:auto;">
            <label style="margin-top:10px;">Layers</label>
            <div id="layerList"></div>
        </div>
    </div>

    <!-- Main Canvas Area -->
    <div class="main-content">
        <div class="toolbar">
            <span><i class="fas fa-mouse-pointer"></i> Editor</span>
            <button class="btn btn-primary" onclick="generateZPL()"><i class="fas fa-sync"></i> Update ZPL</button>
        </div>
        <div class="canvas-container">
            <div id="canvasWrapper">
                <canvas id="mainCanvas"></canvas>
            </div>
            <div class="zoom-control">
                <i class="fas fa-minus" style="cursor:pointer" onclick="adjZoom(-0.1)"></i>
                <span id="zoomVal">150%</span>
                <i class="fas fa-plus" style="cursor:pointer" onclick="adjZoom(0.1)"></i>
            </div>
        </div>
    </div>

    <!-- Code Panel -->
    <div class="code-panel">
        <h2>ZPL Output</h2>
        <textarea id="outputCode" style="flex:1; background:transparent; border:none; color:#94a3b8; resize:none; font-family:monospace;" readonly></textarea>
        <button class="btn btn-primary" onclick="downloadCode()" style="margin-top:10px;">Download</button>
    </div>

<script>
    const DPI = 8;
    let items = [
        { id: 1, type: 'text', value: 'STREAMLIT', x: 40, y: 30, h: 40, scale: 1, bold: true, w:0 },
        { id: 2, type: 'barcode', value: '123456', x: 40, y: 80, h: 60, scale: 2, bold: false, w:0 }
    ];
    let selectedId = null;
    let zoom = 1.5;
    let drag = false, resize = false;
    let startPos = {x:0, y:0}, itemStart = {};

    const canvas = document.getElementById('mainCanvas');
    const ctx = canvas.getContext('2d');

    function initCanvas() {
        const w = document.getElementById('canvasW').value;
        const h = document.getElementById('canvasH').value;
        canvas.width = w * DPI; canvas.height = h * DPI;
        setZoom(zoom);
        draw();
    }

    function setZoom(z) {
        zoom = Math.max(0.5, Math.min(3, z));
        document.getElementById('zoomVal').innerText = Math.round(zoom*100)+'%';
        const wrap = document.getElementById('canvasWrapper');
        wrap.style.transform = `scale(${zoom})`;
        wrap.style.width = canvas.width + 'px';
        wrap.style.height = canvas.height + 'px';
    }
    function adjZoom(d) { setZoom(zoom + d); }

    function draw() {
        ctx.fillStyle = 'white'; ctx.fillRect(0,0,canvas.width,canvas.height);

        // Grid
        ctx.strokeStyle = '#f3f4f6'; ctx.lineWidth=1; ctx.beginPath();
        for(let i=0; i<canvas.width; i+=20) { ctx.moveTo(i,0); ctx.lineTo(i,canvas.height); }
        for(let i=0; i<canvas.height; i+=20) { ctx.moveTo(0,i); ctx.lineTo(canvas.width,i); }
        ctx.stroke();

        items.forEach(i => {
            ctx.save(); ctx.translate(i.x, i.y);
            if(i.type === 'text') {
                ctx.fillStyle='black'; ctx.font=(i.bold?'bold ':'')+i.h+'px Arial';
                ctx.textBaseline='top'; ctx.scale(0.8,1); ctx.fillText(i.value,0,0);
                i.w = ctx.measureText(i.value).width * 0.8;
            } else if(i.type === 'barcode') {
                let t = document.createElement('canvas');
                try {
                    JsBarcode(t, i.value, {format:"CODE128", displayValue:true, height:i.h, margin:0, width: Math.max(1, Math.round(i.scale))});
                    ctx.drawImage(t,0,0); i.w=t.width;
                } catch(e){ ctx.fillStyle='red'; ctx.fillText('Err',0,0); i.w=50; }
            } else if(i.type === 'qr') {
                try {
                    let qr=qrcode(0,'M'); qr.addData(i.value); qr.make();
                    let sz = qr.getModuleCount() * Math.max(1, Math.round(i.scale));
                    ctx.fillStyle='black';
                    for(let r=0; r<qr.getModuleCount(); r++){
                        for(let c=0; c<qr.getModuleCount(); c++){
                            if(qr.isDark(r,c)) ctx.fillRect(c*Math.max(1, Math.round(i.scale)), r*Math.max(1, Math.round(i.scale)), Math.max(1, Math.round(i.scale)), Math.max(1, Math.round(i.scale)));
                        }
                    }
                    i.w=sz; i.h=sz;
                } catch(e){ i.w=50; i.h=50; }
            }
            ctx.restore();

            if(i.id === selectedId) {
                ctx.strokeStyle='#4f46e5'; ctx.setLineDash([4,4]); ctx.strokeRect(i.x-2, i.y-2, i.w+4, i.h+4);
                ctx.fillStyle='#4f46e5'; ctx.setLineDash([]);
                ctx.fillRect(i.x+i.w-5, i.y+i.h-5, 10, 10);
            }
        });
        generateZPL();
    }

    function getPos(e) {
        let rect = canvas.getBoundingClientRect();
        let scX = canvas.width/rect.width; let scY = canvas.height/rect.height;
        return { x: (e.clientX-rect.left)*scX, y: (e.clientY-rect.top)*scY };
    }

    canvas.addEventListener('mousedown', e => {
        let pos = getPos(e);
        // Check resize
        for(let i=items.length-1; i>=0; i--){
            if(items[i].id === selectedId) {
                let it = items[i];
                if(pos.x > it.x+it.w-10 && pos.x < it.x+it.w+15 && pos.y > it.y+it.h-10 && pos.y < it.y+it.h+15){
                    resize=true; dragStart=pos; itemStart={...it}; return;
                }
            }
        }
        // Check select
        for(let i=items.length-1; i>=0; i--){
            let it = items[i];
            if(pos.x>it.x && pos.x<it.x+it.w && pos.y>it.y && pos.y<it.y+it.h){
                selectItem(it.id); drag=true; dragStart=pos; itemStart={...it}; return;
            }
        }
        selectedId=null; updateUI(); draw();
    });

    window.addEventListener('mousemove', e => {
        if(!drag && !resize) return;
        let pos = getPos(e);
        let dx = pos.x-dragStart.x; let dy = pos.y-dragStart.y;
        let it = items.find(x=>x.id===selectedId);
        if(drag){ it.x = itemStart.x+dx; it.y=itemStart.y+dy; }
        if(resize){
             if(it.type==='text') it.h = Math.max(10, itemStart.h+dy);
             else { it.scale = Math.max(1, itemStart.scale + (dx/20)); it.h = Math.max(10, itemStart.h+dy); }
        }
        updateUI(); draw();
    });
    window.addEventListener('mouseup', ()=>{drag=false; resize=false;});

    function addItem(t) { items.push({id:Date.now(), type:t, value:'DATA', x:10, y:10, h:30, scale:1, bold:false, w:0}); draw(); renderList(); }
    function deleteItem() { if(selectedId) items=items.filter(x=>x.id!==selectedId); selectedId=null; draw(); renderList(); updateUI(); }
    function selectItem(id) { selectedId=id; renderList(); updateUI(); draw(); }

    function updateItem(k, v) {
        if(!selectedId) return;
        let it = items.find(x=>x.id===selectedId);
        if(k==='value') it.value=v; else if(k==='bold') it.bold=v; else it[k]=parseFloat(v);
        draw();
    }

    function updateUI() {
        let panel = document.getElementById('propPanel');
        if(!selectedId) { panel.classList.remove('active'); return; }
        panel.classList.add('active');
        let it = items.find(x=>x.id===selectedId);
        ['Value','X','Y','H','Scale'].forEach(k => {
            let el = document.getElementById('prop'+k);
            if(el) el.value = it[k.toLowerCase()] || it[k];
        });
        document.getElementById('propBold').checked = it.bold;

        // Toggle visibility
        if(it.type==='text') { document.getElementById('textOptions').classList.remove('hidden'); document.getElementById('propScale').disabled=true; }
        else { document.getElementById('textOptions').classList.add('hidden'); document.getElementById('propScale').disabled=false; }
    }

    function renderList() {
        let d = document.getElementById('layerList'); d.innerHTML='';
        items.forEach(i => {
            let el = document.createElement('div');
            el.className = `layer-item ${i.id===selectedId?'selected':''}`;
            el.innerText = i.type.toUpperCase() + ': ' + i.value.substring(0,10);
            el.onclick = ()=>selectItem(i.id);
            d.appendChild(el);
        });
    }

    function generateZPL() {
        let z = `^XA^PW${canvas.width}^LL${canvas.height}`;
        items.forEach(i => {
            z+=`^FO${Math.round(i.x)},${Math.round(i.y)}`;
            if(i.type==='text') z+=`^A0N,${Math.round(i.h)},${Math.round(i.h)}^FD${i.value}^FS`;
            else if(i.type==='barcode') z+=`^BY${Math.round(i.scale)},2,${Math.round(i.h)}^BCN,${Math.round(i.h)},N,N,N^FD${i.value}^FS`;
            else if(i.type==='qr') z+=`^BQN,2,${Math.round(i.scale)}^FDQA,${i.value}^FS`;
        });
        z+='^XZ';
        document.getElementById('outputCode').value = z;
    }

    function downloadCode() {
        let b = new Blob([document.getElementById('outputCode').value], {type:'text/plain'});
        let a = document.createElement('a'); a.href=URL.createObjectURL(b); a.download='label.zpl'; a.click();
    }

    initCanvas();
    renderList();
</script>
</body>
</html>
"""

# 4. Render the HTML
# height=800 ensures enough vertical space for the interface
components.html(html_code, height=800, scrolling=False)